name: pmultiqc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - multiqc==1.26
  - pandas<=2.0.3
  - pyteomics
  - pyopenms
  - sdrf-pipelines>=0.0.32
  - lxml
  - numpy==1.24.3
  - pyarrow
  - scikit-learn==1.5.0