apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-ingress-controller-http
  namespace: pride-services
  labels:
    app: ingress-nginx-controller
spec:
  type: ExternalName
  externalName: ingress-nginx-ingress-controller-http.ingress.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http